-- Clear existing data to avoid conflicts if script is run multiple times (optional)
-- DELETE FROM order_items; -- If you had order items linked to products/orders
-- DELETE FROM orders;
-- DELETE FROM products;
-- DELETE FROM users; -- Be careful with this if you have specific users you want to keep

-- Sample Product Data (Chinese)
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES
('时尚智能手表 S1', '最新款智能手表，拥有多种健康监测功能和长效电池续航。兼容iOS和安卓系统。', 699.00, '电子产品', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=智能手表S1', 50),
('深度学习入门教程', '一本适合初学者的深度学习实践指南，包含多个案例和代码解析。', 88.50, '图书音像', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=深度学习教程', 120),
('纯棉休闲T恤 (多色可选)', '100%纯棉T恤，舒适透气，简约时尚，多种颜色可选。', 129.00, '服装服饰', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=纯棉T恤', 200),
('不锈钢厨具套装 (5件套)', '高品质不锈钢打造，包含常用厨具，耐用易清洗，是您厨房的好帮手。', 399.00, '家居厨具', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=厨具套装', 75),
('专业跑步鞋 XPro', '轻便减震专业跑步鞋，提供卓越的支撑和舒适度，助您畅跑无忧。', 450.00, '运动户外', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=跑步鞋XPro', 90),
('天然草本精华面膜 (10片)', '蕴含多种天然草本精华，深层补水，提亮肤色，适合各种肤质。', 79.90, '美妆健康', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=草本面膜', 150),
('儿童益智积木套装', '环保材质，色彩鲜艳，多种拼搭方式，激发儿童创造力和想象力。', 188.00, '玩具游戏', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=益智积木', 100),
('高清液晶显示器 27英寸', '27英寸IPS面板，2K高清分辨率，广视角，色彩精准，办公娱乐皆宜。', 1599.00, '电子产品', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=27寸显示器', 30),
('世界名著经典译丛 (精装版)', '收录多部世界文学经典，名家翻译，精美装帧，值得收藏阅读。', 280.00, '图书音像', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=名著译丛', 60),
('女士优雅连衣裙', '新款时尚连衣裙，修身显瘦，面料舒适，适合多种场合穿着。', 320.00, '服装服饰', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=连衣裙', 80),
('多功能榨汁料理机', '一机多用，可榨汁、搅拌、研磨，轻松制作健康饮品和辅食。', 259.00, '家居厨具', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=料理机', 65),
('户外登山背包 50L', '大容量专业登山包，背负系统舒适，防水耐磨，适合长途徒步。', 580.00, '运动户外', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=登山背包', 40),
('氨基酸温和洁面乳', '弱酸性氨基酸配方，温和清洁不紧绷，泡沫细腻，适合敏感肌。', 99.00, '美妆健康', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=洁面乳', 180),
('遥控越野赛车模型', '1:16比例遥控赛车，动力强劲，四轮驱动，体验越野乐趣。', 298.00, '玩具游戏', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=遥控赛车', 70),
('无线蓝牙降噪耳机', '主动降噪技术，音质纯净，佩戴舒适，长效续航，享受沉浸式音乐体验。', 899.00, '电子产品', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=降噪耳机', 55),
('畅销悬疑小说《谜案追踪》', '情节跌宕起伏，悬念丛生，让你欲罢不能的畅销悬疑力作。', 45.00, '图书音像', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=悬疑小说', 250),
('男士商务休闲衬衫', '精选面料，合身剪裁，透气舒适，彰显商务人士干练气质。', 199.00, '服装服饰', 'https://placehold.co/600x400/EAEAEA/AAAAAA?text=男士衬衫', 110);

-- Note: Spring Boot will automatically pick up and run this data.sql file if spring.jpa.defer-datasource-initialization is true (default for embedded DBs)
-- or if spring.sql.init.mode=always is set.
-- Ensure your Product entity and table schema match these columns.
-- The 'id' column is usually auto-generated by JPA (e.g., @GeneratedValue(strategy = GenerationType.IDENTITY)), so it's not included in the INSERT statements here.
-- If your 'id' is not auto-generated or you want to specify it, you'd need to include it and manage sequences or values manually.
-- The application.properties has spring.jpa.hibernate.ddl-auto=update, so the table should be created/updated based on the Product entity.
